services:
  - type: web
    name: oss-fuzzing-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: RENDER_DISK_PATH
        value: /var/data
    disk:
      name: oss-fuzzing-data
      mountPath: /var/data
      sizeGB: 1
